import Head from 'next/head';

import { BookDetailPage } from '@/features/book-detail';

export default function Detail() {
  return (
    <>
      <Head>
        <title>NY | Book detail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BookDetailPage />
      </main>
    </>
  );
}
